/**
 * Assemble ./lang/<code>.js from the per-group JSON in ./lang/_parts/.
 *
 *   node src/i18n/lang/build-lang.mjs
 *
 * The translations are authored as JSON, one file per interface group, because 739 keys
 * x 5 languages is 3695 entries and hand-writing that much JavaScript invites syntax
 * errors that only surface at runtime. JSON also keeps `{count}` placeholders and
 * backticks honest.
 *
 * A key that is absent from a group's JSON is deliberately left OUT of the generated
 * file rather than emitted as null. translate.js falls back with `??`, so an emitted ""
 * would render a blank label, whereas an absent key renders English -- which is the
 * correct outcome for a product name, a sampler name, or anything a translator
 * deliberately left in English. Keeping them absent means the fallback chain does the
 * work and nothing has to remember to check it.
 *
 * Keys whose value must stay English (product and model names, SPDX identifiers, quoted
 * licence terms) are therefore simply not written down. The report below says how many
 * were left, so an accidental omission is visible rather than silent.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { STRINGS } from "../strings.js";
import { LANGUAGES } from "../languages.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const PARTS = join(HERE, "_parts");

// Loading strings.js pulls in the overlays this script is about to regenerate, which is
// circular. Read the catalogue through the same merge the app uses, but tolerate the
// half-built state: the group JSON is the only thing consulted for values.
const ORDER = Object.keys(STRINGS);
const GROUP_OF = (key) => key.split(".")[0];

const TRANSLATABLE = LANGUAGES.map((l) => l.code).filter((c) => c !== "en");

/** @type {Record<string, Record<string, Record<string, string>>>} */
const parts = {};
for (const file of readdirSync(PARTS).filter((f) => f.endsWith(".json"))) {
  const group = file.replace(/\.json$/, "");
  parts[group] = JSON.parse(readFileSync(join(PARTS, file), "utf8"));
}

const unknown = [];
for (const group of Object.keys(parts)) {
  for (const key of Object.keys(parts[group])) {
    if (!ORDER.includes(key)) unknown.push(`${group}:${key}`);
  }
}
if (unknown.length) {
  throw new Error(`translation JSON references keys that do not exist:\n  ${unknown.join("\n  ")}`);
}

const counts = {};
for (const code of TRANSLATABLE) {
  const out = {};
  const missing = [];
  let done = 0;

  for (const key of ORDER) {
    const entry = parts[GROUP_OF(key)]?.[key];
    if (!entry) {
      missing.push(key);
      continue;
    }
    const text = entry[code];
    if (typeof text !== "string" || text.trim() === "") {
      missing.push(key);
      continue;
    }
    out[key] = text;
    done += 1;
  }

  const lang = LANGUAGES.find((l) => l.code === code);
  const header = `// ${lang.label} translation -- GENERATED by ./build-lang.mjs, do not edit.
// Edit src/i18n/lang/_parts/*.json and re-run the script.
//
// ${done} of ${ORDER.length} strings translated. Keys that are absent fall back to
// English, which is intended for product names, sampler names, SPDX identifiers and
// quoted licence terms -- and for anything not yet translated.

export const ${code}Strings = {
`;

  const body = ORDER.filter((k) => k in out)
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(out[k])},`)
    .join("\n");

  writeFileSync(join(HERE, `${code}.js`), `${header}${body}\n};\n`, "utf8");

  counts[code] = { done, total: ORDER.length, missing };
  const pct = ((done / ORDER.length) * 100).toFixed(1);
  console.log(`  ${code}.js  ${done}/${ORDER.length} (${pct}%)`);
}

writeFileSync(
  join(HERE, "coverage.json"),
  JSON.stringify(
    Object.fromEntries(Object.entries(counts).map(([c, v]) => [c, { done: v.done, total: v.total }])),
    null,
    2
  ) + "\n",
  "utf8"
);

const code = TRANSLATABLE[0];
if (counts[code] && counts[code].missing.length) {
  console.log(`\n  ${counts[code].missing.length} keys left in English, e.g.:`);
  for (const key of counts[code].missing.slice(0, 12)) {
    console.log(`    ${key} :: ${STRINGS[key]?.en ?? ""}`);
  }
}