// Italiano translation -- GENERATED by ./build-lang.mjs, do not edit.
// Edit src/i18n/lang/_parts/*.json and re-run the script.
//
// 0 of 739 strings translated. Keys that are absent fall back to
// English, which is intended for product names, sampler names, SPDX identifiers and
// quoted licence terms -- and for anything not yet translated.

export const itStrings = {

};
