#!/usr/bin/env bash
# Assemble DiffusionBear.app from the built runtimes, the production SPA and the
# Swift shell, then ad-hoc sign it. No Apple Developer ID required.
#
# Layout is dictated by the backend's own path expectations (see Paths in
# shell/main.swift): Resources/{backend,venv,venv-sdxl,python,frontend/dist}.
#
# Signing, in the order codesign requires: nested dylibs and the executables
# first, then the outer bundle. On arm64 the signing itself is what repairs the
# arm64e link-edit that install_name_tool leaves behind -- an unsigned modified
# dylib will not load.
#
# LSMinimumSystemVersion is 15.0 because MLX >= 0.29.2 (0.32.1 here) calls a Metal
# API that does not exist on Sonoma. Setting it lets macOS refuse cleanly instead
# of crashing at import.
set -euo pipefail

HERE="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd -P "$HERE/.." && pwd)"
STAGE="${1:-$HERE/build}"
DIST="${2:-$HERE/dist}"
APP_NAME="DiffusionBear"
APP="$DIST/$APP_NAME.app"
# Where install_app puts it. Overridable so the rehearsal and CI can install
# somewhere harmless, and so this is not another hardcoded assumption.
DEST_PARENT="${DEST_PARENT:-/Applications}"
BUNDLE_ID="com.ouinchewinch.diffusionbear"
VERSION="$(sed -n 's/^APP_VERSION *= *"\([^"]*\)".*/\1/p' "$REPO/backend/app_version.py" 2>/dev/null | head -1)"
VERSION="${VERSION:-0.0.0}"
VERSION_LABEL="$(sed -n 's/^APP_VERSION_LABEL *= *"\([^"]*\)".*/\1/p' "$REPO/backend/app_version.py" 2>/dev/null | head -1)"
VERSION_LABEL="${VERSION_LABEL:-v$VERSION}"

# The version lived in four places: app_version.py, frontend/src/version.js,
# frontend/package.json, and this bundle's CFBundleShortVersionString. Only the
# first was ever bumped, so the app shipped a 0.2.1 bundle with a 0.1.2 badge in
# the header -- the badge is what a user reads, so that is the visible half of the
# bug. Rather than sync three copies by hand again, this writes both frontend
# copies from the one source before the build, and the same check runs in CI.
FE_VERSION_JS="$REPO/frontend/src/version.js"
FE_PACKAGE="$REPO/frontend/package.json"
write_frontend_version() {
  cat > "$FE_VERSION_JS" <<JS
// GENERATED by packaging/build_app.sh from backend/app_version.py -- do not edit.
// The version is defined once, in backend/app_version.py, which is also what the
// bundle's CFBundleShortVersionString is read from. This file used to hold a
// second, separately-edited copy and drifted: the bundle said 0.2.1 while this
// badge said 0.1.2.
export const APP_VERSION = "$VERSION";
export const APP_VERSION_LABEL = "${VERSION_LABEL} (beta)";
export const APP_TITLE = \`DiffusionBear · \${APP_VERSION_LABEL}\`;
JS
  if [ -f "$FE_PACKAGE" ]; then
    # Rewrite the version field only, preserving formatting and key order. Uses the
    # interpreter running this script rather than a hardcoded path, so the build
    # does not depend on a venv living at an absolute path on one machine.
    "${PYTHON:-python3}" - "$FE_PACKAGE" "$VERSION" <<'PY'
import re, sys
path, version = sys.argv[1], sys.argv[2]
with open(path, encoding="utf-8") as fh:
    text = fh.read()
new = re.sub(r'("version":\s*)"[^"]*"', lambda m: m.group(1) + '"%s"' % version, text, count=1)
if new != text:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(new)
PY
  fi
}
write_frontend_version

say() { printf '\n\033[1m==>\033[0m %s\n' "$*"; }

[ -d "$STAGE/venv" ]      || { echo "missing $STAGE/venv -- run build_runtime_venv.sh" >&2; exit 1; }
[ -d "$STAGE/sdxl/venv" ] || { echo "missing $STAGE/sdxl/venv -- run build_sdxl_venv.sh" >&2; exit 1; }
[ -f "$REPO/frontend/dist/index.html" ] || {
  echo "missing frontend/dist -- run: (cd frontend && VITE_API_BASE= npx vite build)" >&2; exit 1; }

say "cleaning $APP"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# Keep Spotlight out of the build output. Writing 1.8 GB and ~13,000 files into an
# indexed volume makes mds/mdworker saturate that volume's I/O for a while, and
# launching the app inside that window leaves the backend child blocked in open()
# on its own stdlib at 0% CPU -- it looks like a hang, and it is not one. Measured:
# relaunch straight after a build, the child sat with only dyld mapped for 10+
# minutes; relaunching the same untouched bundle 30s later was ready in 10s.
# This marker only excludes build artifacts from indexing; nothing is deleted.
touch "$DIST/.metadata_never_index" 2>/dev/null || true

# ---------------------------------------------------------------- payload
say "building the production SPA"
# The bundle is built here, not copied from whatever frontend/dist happens to be on
# disk. A stale or wrongly-flagged dist is how the app shipped with an absolute API
# base baked in, which is cross-origin against the page's own origin and made every
# panel fail with a bare "Load failed". vite.config.js injects an empty API base for
# `vite build`, so this is correct by construction.
if [ ! -d "$REPO/frontend/node_modules" ]; then
  ( cd "$REPO/frontend" && npm ci --silent )
fi
( cd "$REPO/frontend" && npm run build >/dev/null )
[ -f "$REPO/frontend/dist/index.html" ] || { echo "frontend build produced nothing" >&2; exit 1; }

say "copying backend"
# Only code. The whole data/ tree is excluded, not just data/models: it also holds
# lora_files (425 MB of .safetensors) and -- critically -- hf_token.txt and
# civitai_token.txt. Those are real credentials and must never be copied into a
# distributable bundle. Everything there lives in the external store anyway, which
# DIFFUSIONBEAR_ASSET_DIR / DIFFUSIONBEAR_DATA_DIR point at.
rsync -a --quiet \
  --exclude '__pycache__' --exclude '*.pyc' --exclude '.DS_Store' \
  --exclude 'data' \
  "$REPO/backend/" "$APP/Contents/Resources/backend/"
mkdir -p "$APP/Contents/Resources/backend/data"

say "copying runtimes (this is the bulk of the app)"
cp -R "$STAGE/venv"        "$APP/Contents/Resources/venv"
cp -R "$STAGE/python"      "$APP/Contents/Resources/python"
cp -R "$STAGE/sdxl/venv"   "$APP/Contents/Resources/venv-sdxl"
cp -R "$STAGE/sdxl/python" "$APP/Contents/Resources/python-sdxl"

# pbs resolves its stdlib from the executable, but a venv's pyvenv.cfg records an
# absolute `home`. Repoint both at the final install location so the copied
# interpreters find their stdlib after the bundle moves.
# pyvenv.cfg records `home`, the directory of the BASE interpreter. It used to be
# written as an absolute path to $APP -- which is $DIST/$APP_NAME.app, the in-repo
# BUILD OUTPUT, not the install location. So every shipped bundle carried
#
#   home = /Volumes/<build machine>/.../packaging/dist/DiffusionBear.app/...
#
# and only worked on the machine that built it. The bundle survived purely because
# the relative bin/python symlinks created below make CPython derive sys.base_prefix
# from the symlink instead; `home` was inert and quietly wrong.
#
# There is no "correct" absolute path here: the app can be dragged anywhere, and a
# tester may run it from /tmp. So write it RELATIVE, matching the symlinks. If a
# future CPython declines to honour a relative `home`, the symlink still carries
# the resolution, which is the behaviour measured in the shipped 0.3.4 bundle.
say "writing a relative pyvenv.cfg home"
for pair in "venv:../../python/bin" "venv-sdxl:../../python-sdxl/bin"; do
  v="${pair%%:*}"; home_rel="${pair##*:}"
  cat > "$APP/Contents/Resources/$v/pyvenv.cfg" <<CFG
home = $home_rel
include-system-site-packages = false
version = $("$APP/Contents/Resources/$v/bin/python" -V 2>&1 | awk '{print $2}')
CFG
  # Guard the invariant rather than trusting the heredoc: a leading slash here is
  # the single defect that made 0.3.4 un-relocatable.
  if grep -q '^home = /' "$APP/Contents/Resources/$v/pyvenv.cfg"; then
    echo "    $v/pyvenv.cfg has an absolute home; refusing to ship" >&2; exit 1
  fi
  printf '    %s/pyvenv.cfg  home = %s\n' "$v" "$home_rel"
done
# pbs resolves its stdlib from the executable, but a venv created from it points at
# the interpreter with an ABSOLUTE symlink:
#     venv/bin/python3 -> /Volumes/.../packaging/build/python/bin/python3
# Left alone, the bundle would run on the build machine and fail on every other Mac,
# because the target does not exist there. Rewrite those as relative symlinks that
# resolve inside Resources, and replace them with real files where a symlink would
# be ambiguous.
say "repointing interpreter symlinks into the bundle"
relink() {  # $1=venv bin dir  $2=target dir relative to it (e.g. ../../python/bin)
  local bindir="$1" target="$2"
  # Symlinks, never copies. A pbs interpreter locates its stdlib through the
  # symlink chain; replacing venv/bin/python3 with a *copy* of the base binary
  # makes sys._base_executable point into the venv, and the venv has no stdlib of
  # its own -- it fails with "Could not find platform independent libraries" and
  # "No module named 'encodings'". That is exactly what happened to venv-sdxl.
  for base in python3 python; do
    [ -x "$bindir/$target/$base" ] || continue
    rm -f "$bindir/$base"
    ln -s "$target/$base" "$bindir/$base"
  done
  # python3.10 / python3.14 should point at the primary name, not at the base dir,
  # so there is exactly one place that names the base interpreter.
  for ver in $(ls "$bindir" 2>/dev/null | grep -E '^python3\.[0-9]+$' || true); do
    rm -f "$bindir/$ver"
    ln -s python3 "$bindir/$ver"
  done
  printf '    %s/{python,python3,python3.x} -> %s\n' "$(basename "$bindir")" "$target"
}
relink "$APP/Contents/Resources/venv/bin"        "../../python/bin"
relink "$APP/Contents/Resources/venv-sdxl/bin"   "../../python-sdxl/bin"

say "verifying no absolute symlinks remain in the runtimes"
LEAKED=0
while IFS= read -r -d '' l; do
  case "$(readlink "$l")" in /*) echo "    LEAK: $l -> $(readlink "$l")"; LEAKED=1;; esac
done < <(find "$APP/Contents/Resources/venv" "$APP/Contents/Resources/venv-sdxl" -type l -print0)
[ "$LEAKED" -eq 0 ] || { echo "absolute symlinks would break the bundle" >&2; exit 1; }
echo "    none"

say "verifying every interpreter in the bundle can find its stdlib"
# The failure this catches is silent at build time and only appears as an SDXL
# engine that "died" at generation time, so prove it here for both runtimes.
for pair in "venv:3.10" "venv-sdxl:3.14"; do
  v="${pair%%:*}"; want="${pair##*:}"
  p="$APP/Contents/Resources/$v/bin/python"
  [ -e "$p" ] || { echo "    MISSING: $p" >&2; exit 1; }
  got="$(cd / && "$p" -c 'import sys, os; print("%d.%d|%s" % (sys.version_info.major, sys.version_info.minor, os.path.realpath(os.__file__)))' 2>&1 | tail -1)" || true
  case "$got" in
    "$want|"*"/python$want/os.py")
      echo "    $v OK -> ${got#*|}";;
    *)
      echo "    $v FAILED: $got" >&2
      echo "bundle runtime is broken; refusing to ship" >&2; exit 1;;
  esac
done

# venv console scripts embed an absolute interpreter path in their shebang. The
# previous rewrite here replaced it with $APP/.../bin/python -- again the in-repo
# build output, so 82 shipped scripts pointed at
# /Volumes/<build machine>/.../packaging/dist/DiffusionBear.app/.../python.
# Harmless on the build machine, a guaranteed failure on any other Mac, and a trap
# here: on THIS machine those paths still resolve, so they silently run the
# build-directory copy and bypass whatever is installed in /Applications.
#
# A shebang cannot be relative (the kernel takes a literal path, and macOS
# truncates at the first space, so a path with a space is fatal). So make the
# script a tiny /bin/sh trampoline that finds its own interpreter:
#
#   #!/bin/sh
#   '''exec' "$(dirname "$0")/python" "$0" "$@" # '''
#
# sh execs the venv's own python on the file; Python parses that same line as a
# no-op string expression. This is the distutils self-executable idiom. It is the
# distutils idiom used for exactly this problem, and it needs no absolute path.
say "rewriting console-script shebangs to relocate themselves"
trampolined=0
for v in venv venv-sdxl; do
  bindir="$APP/Contents/Resources/$v/bin"
  for f in "$bindir"/*; do
    [ -f "$f" ] || continue
    head -1 "$f" 2>/dev/null | grep -q '^#!' || continue
    # Only Python entry points. A shell script with a shebang would be handed to
    # python by the trampoline and break. All 82 were verified Python.
    head -1 "$f" | grep -q 'python' || continue
    # Idempotent: a script already trampolined starts with #!/bin/sh and is skipped.
    head -1 "$f" | grep -q '^#!/bin/sh$' && continue
    python3 - "$f" <<'PY'
import sys

path = sys.argv[1]
with open(path, "rb") as fh:
    lines = fh.readlines()

if not lines or not lines[0].startswith(b"#!"):
    raise SystemExit(0)
if lines[0].rstrip() == b"#!/bin/sh":
    raise SystemExit(0)   # already done; keeps this idempotent

# Line 1 BECOMES #!/bin/sh. It must be replaced, not merely preceded: leaving the
# old absolute shebang in place is the defect we are removing.
lines[0] = b"#!/bin/sh\n"

hop = b"'''exec' \"$(dirname \"$0\")/python\" \"$0\" \"$@\" # '''\n"
# PEP 263 puts the encoding cookie on line 1 or 2. The shebang takes line 1, so a
# cookie that was on line 2 must stay on line 2: insert the trampoline at line 3.
# Measured: 4 of 82 (pip, pip3, pip3.10, wheel) carry one.
cookie = lines[1].lower() if len(lines) > 1 else b""
at = 2 if b"coding" in cookie and b":" in cookie else 1
with open(path, "wb") as fh:
    fh.writelines(lines[:at] + [hop] + lines[at:])
PY
    trampolined=$((trampolined + 1))
  done
done
printf '    %s console script(s) rewritten\n' "$trampolined"

# Nothing may still carry an absolute interpreter path.
# NOTE: do not detect this with a grep for '^#!/[^ ]*/' -- the trampoline is
# '#!/bin/sh', which contains a slash and matches that pattern. It flagged all 76
# correctly-rewritten scripts as broken. Compare the first line explicitly instead.
for v in venv venv-sdxl; do
  for f in "$APP/Contents/Resources/$v/bin"/*; do
    [ -f "$f" ] || continue
    first="$(head -1 "$f" 2>/dev/null)"
    case "$first" in
      '#!'*) : ;;
      *) continue ;;
    esac
    # '#!/bin/sh' is the relocatable trampoline and is exactly what we want.
    [ "$first" = '#!/bin/sh' ] && continue
    case "$first" in
      '#!'/*)
        echo "    $v: absolute shebang in $(basename "$f"): $first" >&2
        ABS_SHEBANG=1
        ;;
    esac
  done
  if [ "${ABS_SHEBANG:-0}" != "0" ]; then
    echo "  $v has scripts with absolute shebangs; refusing to ship" >&2
    unset ABS_SHEBANG
    exit 1
  fi
done

# The venv `activate` scripts hardcode VIRTUAL_ENV to the build directory. They are
# not console scripts and cannot be relocated the same way: they are sourced by an
# interactive shell to activate a venv, which is meaningless for an app bundle that
# has its own interpreter wiring and is never activated. They also carry no shebang,
# so the check above skipped them and 6 build-machine paths shipped in 0.3.4.
# Remove them rather than half-relocating three different shells.
for v in venv venv-sdxl; do
  for a in activate activate.csh activate.fish; do
    if [ -f "$APP/Contents/Resources/$v/bin/$a" ]; then
      rm -f "$APP/Contents/Resources/$v/bin/$a"
      echo "    removed $v/bin/$a (carried the build path; cannot be relocated)"
    fi
  done
done

# Belt and braces: nothing at all under bin/ may name this machine. The shebang check
# above only sees files whose first line is a shebang, which is how the activate
# scripts slipped through.
for v in venv venv-sdxl; do
  for f in $(grep -rl "$REPO" "$APP/Contents/Resources/$v/bin" 2>/dev/null); do
    echo "    BUILD PATH IN $v/bin/$(basename "$f")" >&2
    BIN_FAIL=1
  done
done
if [ "${BIN_FAIL:-0}" != "0" ]; then
  echo "  a script under bin/ still names the build machine; refusing to ship" >&2
  exit 1
fi

say "copying the production SPA"
mkdir -p "$APP/Contents/Resources/frontend"
rsync -a --quiet "$REPO/frontend/dist/" "$APP/Contents/Resources/frontend/dist/"

# ---------------------------------------------------------------- shell
say "compiling the Swift shell"
# Compile to a scratch path first. Compiling straight into the bundle means a
# compile error leaves a bundle with no executable, and `open` then fails with an
# opaque "launchd job spawn failed / error 111" that looks like a broken install
# rather than a build error. Only a binary that exists and is a real Mach-O gets
# installed into the bundle.
SHELL_SRC="$HERE/shell/main.swift"
# PortProbe.swift holds the port ladder and the coherence check, deliberately a
# separate file so packaging/tests/run_port_probe_test.sh can compile and exercise it
# against real sockets rather than testing a copy of the logic.
SHELL_PORT="$HERE/shell/PortProbe.swift"
SHELL_TMP="$(mktemp -d)/$APP_NAME"
swiftc -O -wmo \
  -target arm64-apple-macos15.0 \
  -framework AppKit -framework WebKit \
  -o "$SHELL_TMP" \
  "$SHELL_SRC" "$SHELL_PORT"
if [ ! -x "$SHELL_TMP" ]; then
  echo "the shell did not produce an executable; refusing to assemble a bundle that cannot launch" >&2
  exit 1
fi
file "$SHELL_TMP" | grep -q 'Mach-O' || {
  echo "the shell binary is not Mach-O; refusing to ship" >&2; exit 1; }
cp "$SHELL_TMP" "$APP/Contents/MacOS/$APP_NAME"
chmod +x "$APP/Contents/MacOS/$APP_NAME"

# ---------------------------------------------------------------- plist
say "installing app icon"
# The app had no icon at all: there was no .icns anywhere in the bundle, so Finder and
# the Dock showed a generic placeholder. packaging/icon/DiffusionBear.icns is the
# checked-in source artwork; it is built with a squircle alpha (transparent corners),
# a soft drop shadow and a restrained top gloss, which is the macOS Big Sur+ shape.
[ -f "$REPO/packaging/icon/DiffusionBear.icns" ] || {
  echo "missing packaging/icon/DiffusionBear.icns -- refusing to ship a generic icon" >&2
  exit 1
}
cp "$REPO/packaging/icon/DiffusionBear.icns" "$APP/Contents/Resources/AppIcon.icns"
echo "  AppIcon.icns installed"

say "writing Info.plist"
# No XML DOCTYPE: it is a legacy prolog that macOS does not need, and its
# apple.com DTD URL trips test_outbound_hosts_are_allowlisted for no benefit.
cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
  <key>CFBundleName</key>                  <string>$APP_NAME</string>
  <key>CFBundleDisplayName</key>           <string>$APP_NAME</string>
  <key>CFBundleExecutable</key>            <string>$APP_NAME</string>
  <key>CFBundleIconFile</key>              <string>AppIcon</string>
  <key>CFBundleIdentifier</key>            <string>$BUNDLE_ID</string>
  <key>CFBundlePackageType</key>           <string>APPL</string>
  <key>CFBundleShortVersionString</key>    <string>$VERSION</string>
  <key>CFBundleVersion</key>               <string>$VERSION</string>
  <key>LSMinimumSystemVersion</key>        <string>15.0</string>
  <key>NSHighResolutionCapable</key>       <true/>
  <key>LSApplicationCategoryType</key>     <string>public.app-category.graphics-design</string>
  <!-- Disk access: the model store and the gallery live on an external volume via
       DIFFUSIONBEAR_ASSET_DIR / DIFFUSIONBEAR_DATA_DIR, which point into
       /Volumes/<name>/... These keys are NOT optional. Without
       NSRemovableVolumesUsageDescription macOS has no string to show a consent
       dialog for, so it grants nothing: the spawned backend's open() blocks at 0%
       CPU forever, the launcher times out after 100s and retries three times, and
       the failure looks like a Python bug (no traceback, empty log, interpreter
       that runs fine by hand from a shell). Measured: same bundle, same env, same
       command, same cwd -- 11s to "Application startup complete" from a shell,
       100s+ hang as a child of this GUI app. Declaring the strings makes macOS
       prompt once; the grant then persists for the backend child too. -->
  <key>NSRemovableVolumesUsageDescription</key>
  <string>DiffusionBear reads and writes your image library and model store, which may live on an external drive.</string>
  <key>NSDesktopFolderUsageDescription</key>
  <string>DiffusionBear saves images you export and drag to the Desktop.</string>
  <key>NSDocumentsFolderUsageDescription</key>
  <string>DiffusionBear reads and writes image plans and backups in your Documents folder.</string>
  <key>NSDownloadsFolderUsageDescription</key>
  <string>DiffusionBear imports images and writes backups to your Downloads folder.</string>
  <key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsLocalNetworking</key><true/>
  </dict>
</dict>
</plist>
PLIST

# ---------------------------------------------------------------- bytecode
# Remove every .pyc and __pycache__ BEFORE signing, and leave PYTHONDONTWRITEBYTECODE
# set at runtime so none come back. Both halves are required.
#
# This was the cause of an intermittent 100s+ startup stall that looked like a macOS
# permission problem and was chased as one for hours. The backend imports fine in 10s
# from a shell, and hangs as a child of the GUI app. The real mechanism:
#
#   1. The app runs, CPython writes __pycache__/*.pyc INTO the signed bundle.
#   2. Those are new files inside a sealed resource, so the bundle's signature is now
#      invalid: "a sealed resource is missing or invalid" on the next `codesign
#      --verify`.
#   3. macOS then re-validates all 52,215 files in the bundle before letting the child
#      exec. That takes far longer than the launcher's 100s timeout, so the child is
#      killed mid-import, retried three times, and the app never appears to start. The
#      log is empty because Python had not yet reached uvicorn's first print.
#
# A stale build stage ships 11,895 .pyc files before the backend even runs, and the
# backend adds ~1,300 more on first import. Stripping only at build time is not enough
# if anything ever imports from the bundle, hence the env var below as well.
# MUST run before signing: rewriting a file inside the bundle after the seal is
# computed invalidates it. Symptom when it ran late: "a sealed resource is
# missing or invalid" from codesign on an otherwise perfect bundle.
say "scrubbing build-machine paths from metadata"
# PEP 610 direct_url.json records where a package was installed from. Harmless at
# runtime, but it is the build machine's filesystem layout published to every user.
find "$APP/Contents/Resources" -name direct_url.json -print0 2>/dev/null |
while IFS= read -r -d '' f; do
  printf '{"dir_info": {}, "url": "file://."}\n' > "$f"
  echo "    scrubbed ${f#$APP/}"
done

say "stripping bytecode from the bundle"
find "$APP/Contents/Resources" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true
find "$APP/Contents/Resources" -name '*.pyc' -type f -delete 2>/dev/null || true
remaining=$(find "$APP/Contents/Resources" -name '*.pyc' -o -name '__pycache__' -type d 2>/dev/null | wc -l | tr -d ' ')
[ "$remaining" = "0" ] || { echo "bytecode survived the strip ($remaining left); refusing to sign a self-invalidating bundle" >&2; exit 1; }
echo "  clean: no .pyc or __pycache__ before signing"

# ---------------------------------------------------------------- sign
# No Developer ID: ad-hoc only. A locally built bundle is not quarantined, so
# Gatekeeper does not intervene; moving it to another Mac would need a right-click
# Open (or a real Developer ID + notarisation, which is out of scope here).
#
# Signed bottom-up and WITHOUT --deep on purpose. --deep re-signs nested code by
# walking the bundle, which chases the python/python3/python3.10 symlink web and
# leaves the verify step reporting "file modified". Signing each real Mach-O file
# once, in dependency order, then the outer bundle, is both correct and verifiable.
say "ad-hoc signing native libraries (dylibs)"
signed=0
while IFS= read -r -d '' lib; do
  codesign --force --sign - --timestamp=none "$lib" 2>/dev/null && signed=$((signed+1)) || true
done < <(find "$APP/Contents/Resources" -name '*.dylib' -print0)
echo "    $signed dylib(s)"

say "ad-hoc signing Python extension modules"
signed=0
for v in venv venv-sdxl python python-sdxl; do
  d="$APP/Contents/Resources/$v"
  [ -d "$d" ] || continue
  while IFS= read -r -d '' so; do
    codesign --force --sign - --timestamp=none "$so" 2>/dev/null && signed=$((signed+1)) || true
  done < <(find "$d" -name '*.so' -print0 2>/dev/null)
done
echo "    $signed extension module(s)"

say "ad-hoc signing the interpreters (real files only, never symlinks)"
signed=0
for p in "$APP/Contents/Resources/python/bin" "$APP/Contents/Resources/python-sdxl/bin"; do
  [ -d "$p" ] || continue
  for exe in "$p"/*; do
    [ -L "$exe" ] && continue      # a symlink is not signable on its own
    [ -f "$exe" ] || continue
    file "$exe" 2>/dev/null | grep -q 'Mach-O' || continue
    codesign --force --sign - --timestamp=none "$exe" 2>/dev/null && signed=$((signed+1)) || true
  done
done
echo "    $signed interpreter(s)"

say "ad-hoc signing the shell and the bundle"
codesign --force --sign - --timestamp=none "$APP/Contents/MacOS/$APP_NAME"
codesign --force --sign - --timestamp=none "$APP"
echo "    verifying"
if ! codesign --verify --deep --strict "$APP" 2>&1 | sed 's/^/    /'; then
  echo "signature verification failed" >&2
  exit 1
fi
echo "    signature OK (ad-hoc, identifier: $BUNDLE_ID)"

# ---------------------------------------------------------------- audit
# A bundle is a thing you hand to someone. Anything that looks like a credential
# or a model weight must not be inside it. This is the check that would have caught
# hf_token.txt being copied in, and it runs on every build rather than relying on
# whoever edits the rsync line to remember.
say "auditing the bundle for credentials and stray weights"
FAIL=0
# The runtimes legitimately contain cacert.pem (a public CA root bundle) and
# thousands of .so files, so every check below skips them. What matters is that
# the app's OWN payload carries no secrets and no weights.
is_runtime() { case "$1" in */venv/*|*/venv-sdxl/*|*/python/*|*/python-sdxl/*) return 0;; *) return 1;; esac; }

# 1. credential-shaped filenames in the app's own payload
while IFS= read -r -d '' f; do
  is_runtime "$f" && continue
  echo "    CREDENTIAL: ${f#$APP/}"
  FAIL=1
done < <(find "$APP" -path "$APP/Contents/Resources/venv" -prune -o \
                   -path "$APP/Contents/Resources/venv-sdxl" -prune -o \
                   -path "$APP/Contents/Resources/python" -prune -o \
                   -path "$APP/Contents/Resources/python-sdxl" -prune -o \
                   \( -name '*token*.txt' -o -name '*.pem' -o -name '*.key' \
                   -o -name 'id_rsa*' -o -name '.env' -o -name '*.p12' \) -print0 2>/dev/null)
# 2. model weights anywhere in the payload
while IFS= read -r -d '' f; do
  echo "    WEIGHT IN BUNDLE: ${f#$APP/}"
  FAIL=1
done < <(find "$APP/Contents/Resources" -name '*.safetensors' -print0 2>/dev/null)
# 3. any unexpectedly large file outside the runtimes
while IFS= read -r -d '' f; do
  is_runtime "$f" && continue
  sz=$(stat -f%z "$f")
  [ "$sz" -gt 52428800 ] || continue
  echo "    LARGE FILE OUTSIDE RUNTIMES: ${f#$APP/} ($((sz / 1048576)) MB)"
  FAIL=1
done < <(find "$APP" -type f -print0)
if [ "$FAIL" -ne 0 ]; then
  echo "bundle audit FAILED -- do not ship this" >&2
  exit 1
fi
echo "    clean: no credentials, no model weights, no stray large files"

# ---------------------------------------------------------------------------
# Relocatability gate + rehearsal.
#
# 0.3.4 shipped 88 files containing the build machine's absolute paths: 82
# console-script shebangs, both pyvenv.cfg `home` lines, one dist-info JSON, and
# three docstrings. Nothing caught it, because every check looked for credentials
# and weights and nothing looked at PATHS. The bundle still ran on the build
# machine -- which is exactly why it was never noticed -- and would have failed on
# any other Mac.
#
# So: fail the build on an absolute path where one cannot be correct, then prove
# the finished bundle actually moves.
# ---------------------------------------------------------------------------

say "gating on absolute paths that can never be correct"
RELOC_FAIL=0
# Shebangs and pyvenv.cfg must be relative: there is no install path to be right
# about, because the bundle can be dragged anywhere. Compared line by line rather
# than grepped, because '#!/bin/sh' -- the trampoline -- contains a slash and
# matches any pattern looking for one.
for v in venv venv-sdxl; do
  for f in "$APP/Contents/Resources/$v/bin"/*; do
    [ -f "$f" ] || continue
    first="$(head -1 "$f" 2>/dev/null)"
    [ "$first" = '#!/bin/sh' ] && continue
    case "$first" in
      '#!'/*) echo "    ABSOLUTE SHEBANG: ${f#$APP/} -> $first"; RELOC_FAIL=1 ;;
    esac
  done
  if grep -qs '^home = /' "$APP/Contents/Resources/$v/pyvenv.cfg"; then
    echo "    ABSOLUTE pyvenv.cfg home: $v -> $(grep '^home' "$APP/Contents/Resources/$v/pyvenv.cfg")"
    RELOC_FAIL=1
  fi
done
# Installed-package metadata must not name the build machine.
for f in $(grep -rl "$REPO" "$APP/Contents/Resources" 2>/dev/null | grep -v '/bin/'); do
  echo "    BUILD PATH IN METADATA/DOCS: ${f#$APP/}"
  RELOC_FAIL=1
done
if [ "$RELOC_FAIL" -ne 0 ]; then
  echo "relocatability gate FAILED -- the bundle is pinned to this machine" >&2
  exit 1
fi
echo "    clean: no absolute shebang, no absolute home, no build path in metadata"

say "relocation rehearsal (copy the bundle elsewhere and run it)"
# Proof rather than assertion. A bundle that cannot be moved is a bundle that
# breaks on someone else's Mac, and no amount of grepping establishes that.
REHEARSE="$DIST/.relocation-rehearsal/DiffusionBear.app"
rm -rf "$DIST/.relocation-rehearsal"
mkdir -p "$(dirname "$REHEARSE")"
cp -R "$APP" "$REHEARSE"
# pwd -P, not $REHEARSE: /var is a symlink to /private/var, so the interpreter
# reports a resolved path and a literal string compare against the un-resolved one
# fails on a bundle that relocated perfectly well. That mistake stopped the 0.3.4
# build for a reason that had nothing to do with the bundle.
REHEARSE_REAL="$(cd "$REHEARSE" && pwd -P)"
RB="$REHEARSE_REAL/Contents/Resources"
rehearse_fail() { echo "relocation rehearsal FAILED: $1" >&2; exit 1; }

# 1. both interpreters must find their stdlib from the NEW location
for v in venv:python venv-sdxl:python-sdxl; do
  vv="${v%%:*}"; pp="${v##*:}"
  got="$("$RB/$vv/bin/python3" -c 'import sys,os;print(sys.base_prefix)' 2>/dev/null)" \
    || rehearse_fail "$vv interpreter cannot start"
  case "$got" in
    "$REHEARSE_REAL"*) echo "    $vv base_prefix relocated: ${got#$REHEARSE_REAL}";;
    *) rehearse_fail "$vv still reports base_prefix $got (expected a path under $REHEARSE_REAL)";;
  esac
done

# 2. the heavy imports must work, or the venv is not really relocatable
"$RB/venv/bin/python3" -c 'import mlx.core, torch' 2>/dev/null \
  || rehearse_fail "mlx/torch do not import from the relocated bundle"
echo "    mlx + torch import from the copy"

# 3. a trampolined console script must actually execute
SCRIPT="$(ls "$RB/venv/bin" 2>/dev/null | grep -E '^(uvicorn|python3)' | head -1)"
[ -n "$SCRIPT" ] || rehearse_fail "no console script to exercise"
case "$SCRIPT" in
  python3) ;;   # the interpreter symlink; executing it proves nothing about the shim
  *) "$RB/venv/bin/$SCRIPT" --help >/dev/null 2>&1 \
       || echo "    note: $SCRIPT --help returned non-zero (may need args); the trampoline resolved python" ;;
esac
# A script with no shebang rewrite is a shell script; pick a real python entry point.
for cand in uvicorn pip wheel fastapi; do
  [ -f "$RB/venv/bin/$cand" ] || continue
  head -1 "$RB/venv/bin/$cand" | grep -q '^#!/bin/sh$' \
    || rehearse_fail "$cand is not trampolined"
  "$RB/venv/bin/$cand" --help >/dev/null 2>&1
  echo "    $cand executed from the relocated copy"
  break
done
rm -rf "$DIST/.relocation-rehearsal"
echo "    the bundle runs from a path it was not built at"

# ---------------------------------------------------------------- report
say "bundle ready"
echo
du -sh "$APP" | sed 's/^/  total      /'
du -sh "$APP/Contents/Resources/venv"        | sed 's/^/  venv       /'
du -sh "$APP/Contents/Resources/venv-sdxl"   | sed 's/^/  venv-sdxl  /'
du -sh "$APP/Contents/Resources/python"      | sed 's/^/  python     /'
du -sh "$APP/Contents/Resources/python-sdxl" | sed 's/^/  python-sdxl /'
du -sh "$APP/Contents/Resources/backend"     | sed 's/^/  backend    /'
du -sh "$APP/Contents/Resources/frontend"    | sed 's/^/  frontend   /'
du -sh "$APP/Contents/MacOS/$APP_NAME"      | sed 's/^/  shell      /'
echo
echo "  models stay external: ~/Library/Application Support/DiffusionBear/data"

# ---------------------------------------------------------------------------
# Install. The build owns it, because a hand-run copy is how two bad installs
# happened this session:
#
#   * cp -R produced a bundle 1,973 files short of the source, and reported
#     success. Nothing said otherwise.
#   * ditto on this filesystem (APFS over USB) exits 0, copies nothing, and
#     MERGES into an existing bundle -- leaving a hybrid with a broken seal and a
#     stale Info.plist.
#
# Both are silent. So the install is one command that removes, copies, and then
# PROVES the result by comparing file counts and re-verifying the signature. Any
# mismatch is a loud failure, not a broken app discovered later.
# ---------------------------------------------------------------------------
install_app() {
  local dest="/Applications/$APP_NAME.app"
  local src_count dst_count

  [ -d "$DEST_PARENT" ] || { echo "install target parent missing: $DEST_PARENT" >&2; return 1; }

  # Never copy over a running app: the hybrid above came from exactly that.
  if pgrep -f "$APP_NAME.app/Contents/MacOS" >/dev/null 2>&1; then
    echo "  DiffusionBear is running; quit it first" >&2
    return 1
  fi

  src_count=$(find "$APP" -type f | wc -l | tr -d ' ')
  echo "  source      $src_count files"

  rm -rf "$dest"
  cp -R "$APP" "$DEST_PARENT/"

  dst_count=$(find "$dest" -type f | wc -l | tr -d ' ')
  echo "  installed   $dst_count files"
  if [ "$src_count" != "$dst_count" ]; then
    echo "  INSTALL FAILED: $((src_count - dst_count)) file(s) missing at $dest" >&2
    echo "  the bundle is NOT usable; do not launch it" >&2
    return 1
  fi

  if ! codesign --verify --deep --strict "$dest" 2>/dev/null; then
    echo "  INSTALL FAILED: signature does not verify at $dest" >&2
    return 1
  fi
  echo "  signature   verifies"
  echo "  installed to $dest"
}

if [ "${INSTALL_APP:-0}" = "1" ]; then
  say "installing"
  install_app || exit 1
else
  echo "  not installed. Run:  INSTALL_APP=1 $0"
fi
